[package]
name = "sealvault_tools_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.70"
hex = "0.4.3"
log = { version = "0.4.17", features = ["serde"] }
sealvault_core = { path = "../../core" }
tempfile = "3.5.0"
